//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.MaterialesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MATERIALES_BELICOS", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Model")]
    [System.SerializableAttribute()]
    public partial class MATERIALES_BELICOS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARMAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALIBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_MATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_DOTACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MATERIALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARMAMENTO {
            get {
                return this.ARMAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ARMAMENTOField, value) != true)) {
                    this.ARMAMENTOField = value;
                    this.RaisePropertyChanged("ARMAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALIBRE {
            get {
                return this.CALIBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CALIBREField, value) != true)) {
                    this.CALIBREField = value;
                    this.RaisePropertyChanged("CALIBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_MATERIAL {
            get {
                return this.CODIGO_MATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_MATERIALField, value) != true)) {
                    this.CODIGO_MATERIALField = value;
                    this.RaisePropertyChanged("CODIGO_MATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FABRICACION {
            get {
                return this.FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FABRICACIONField, value) != true)) {
                    this.FABRICACIONField = value;
                    this.RaisePropertyChanged("FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_DOTACION {
            get {
                return this.FECHA_DOTACIONField;
            }
            set {
                if ((this.FECHA_DOTACIONField.Equals(value) != true)) {
                    this.FECHA_DOTACIONField = value;
                    this.RaisePropertyChanged("FECHA_DOTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.FECHA_MODIFICACIONField;
            }
            set {
                if ((this.FECHA_MODIFICACIONField.Equals(value) != true)) {
                    this.FECHA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("FECHA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MATERIAL {
            get {
                return this.ID_MATERIALField;
            }
            set {
                if ((this.ID_MATERIALField.Equals(value) != true)) {
                    this.ID_MATERIALField = value;
                    this.RaisePropertyChanged("ID_MATERIAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicio", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _dcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _dc {
            get {
                return this._dcField;
            }
            set {
                if ((this._dcField.Equals(value) != true)) {
                    this._dcField = value;
                    this.RaisePropertyChanged("_dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                if ((this.limitField.Equals(value) != true)) {
                    this.limitField = value;
                    this.RaisePropertyChanged("limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                if ((object.ReferenceEquals(this.sortField, value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfMaterialesModelLLZUzu_Sn", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfMaterialesModelLLZUzu_Sn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.MaterialesService.MaterialesModel[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.MaterialesService.MaterialesModel[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MaterialesModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class MaterialesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ARMAMENTOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALIBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGO_MATERIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_DOTACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_MODIFICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MATERIALField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ARMAMENTO {
            get {
                return this.ARMAMENTOField;
            }
            set {
                if ((object.ReferenceEquals(this.ARMAMENTOField, value) != true)) {
                    this.ARMAMENTOField = value;
                    this.RaisePropertyChanged("ARMAMENTO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALIBRE {
            get {
                return this.CALIBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CALIBREField, value) != true)) {
                    this.CALIBREField = value;
                    this.RaisePropertyChanged("CALIBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO_MATERIAL {
            get {
                return this.CODIGO_MATERIALField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGO_MATERIALField, value) != true)) {
                    this.CODIGO_MATERIALField = value;
                    this.RaisePropertyChanged("CODIGO_MATERIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FABRICACION {
            get {
                return this.FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FABRICACIONField, value) != true)) {
                    this.FABRICACIONField = value;
                    this.RaisePropertyChanged("FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_DOTACION {
            get {
                return this.FECHA_DOTACIONField;
            }
            set {
                if ((this.FECHA_DOTACIONField.Equals(value) != true)) {
                    this.FECHA_DOTACIONField = value;
                    this.RaisePropertyChanged("FECHA_DOTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_MODIFICACION {
            get {
                return this.FECHA_MODIFICACIONField;
            }
            set {
                if ((this.FECHA_MODIFICACIONField.Equals(value) != true)) {
                    this.FECHA_MODIFICACIONField = value;
                    this.RaisePropertyChanged("FECHA_MODIFICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MATERIAL {
            get {
                return this.ID_MATERIALField;
            }
            set {
                if ((this.ID_MATERIALField.Equals(value) != true)) {
                    this.ID_MATERIALField = value;
                    this.RaisePropertyChanged("ID_MATERIAL");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MaterialesService.IMateriales")]
    public interface IMateriales {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/GuardarMaterial", ReplyAction="http://tempuri.org/IMateriales/GuardarMaterialResponse")]
        EMI.Website.MaterialesService.RespuestaServicio GuardarMaterial(EMI.Website.MaterialesService.MATERIALES_BELICOS mat, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/GuardarMaterial", ReplyAction="http://tempuri.org/IMateriales/GuardarMaterialResponse")]
        System.Threading.Tasks.Task<EMI.Website.MaterialesService.RespuestaServicio> GuardarMaterialAsync(EMI.Website.MaterialesService.MATERIALES_BELICOS mat, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/EliminarMaterial", ReplyAction="http://tempuri.org/IMateriales/EliminarMaterialResponse")]
        EMI.Website.MaterialesService.RespuestaServicio EliminarMaterial(int ID, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/EliminarMaterial", ReplyAction="http://tempuri.org/IMateriales/EliminarMaterialResponse")]
        System.Threading.Tasks.Task<EMI.Website.MaterialesService.RespuestaServicio> EliminarMaterialAsync(int ID, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/ObtenerMaterialesPaginados", ReplyAction="http://tempuri.org/IMateriales/ObtenerMaterialesPaginadosResponse")]
        EMI.Website.MaterialesService.ListasServicioOfMaterialesModelLLZUzu_Sn ObtenerMaterialesPaginados(EMI.Website.MaterialesService.Paginacion paginacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/ObtenerMaterialesPaginados", ReplyAction="http://tempuri.org/IMateriales/ObtenerMaterialesPaginadosResponse")]
        System.Threading.Tasks.Task<EMI.Website.MaterialesService.ListasServicioOfMaterialesModelLLZUzu_Sn> ObtenerMaterialesPaginadosAsync(EMI.Website.MaterialesService.Paginacion paginacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/ObtenerMaterialBelico", ReplyAction="http://tempuri.org/IMateriales/ObtenerMaterialBelicoResponse")]
        EMI.Website.MaterialesService.MATERIALES_BELICOS ObtenerMaterialBelico(int ID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMateriales/ObtenerMaterialBelico", ReplyAction="http://tempuri.org/IMateriales/ObtenerMaterialBelicoResponse")]
        System.Threading.Tasks.Task<EMI.Website.MaterialesService.MATERIALES_BELICOS> ObtenerMaterialBelicoAsync(int ID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMaterialesChannel : EMI.Website.MaterialesService.IMateriales, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MaterialesClient : System.ServiceModel.ClientBase<EMI.Website.MaterialesService.IMateriales>, EMI.Website.MaterialesService.IMateriales {
        
        public MaterialesClient() {
        }
        
        public MaterialesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MaterialesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MaterialesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.MaterialesService.RespuestaServicio GuardarMaterial(EMI.Website.MaterialesService.MATERIALES_BELICOS mat, string usuario) {
            return base.Channel.GuardarMaterial(mat, usuario);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.MaterialesService.RespuestaServicio> GuardarMaterialAsync(EMI.Website.MaterialesService.MATERIALES_BELICOS mat, string usuario) {
            return base.Channel.GuardarMaterialAsync(mat, usuario);
        }
        
        public EMI.Website.MaterialesService.RespuestaServicio EliminarMaterial(int ID, string usuario) {
            return base.Channel.EliminarMaterial(ID, usuario);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.MaterialesService.RespuestaServicio> EliminarMaterialAsync(int ID, string usuario) {
            return base.Channel.EliminarMaterialAsync(ID, usuario);
        }
        
        public EMI.Website.MaterialesService.ListasServicioOfMaterialesModelLLZUzu_Sn ObtenerMaterialesPaginados(EMI.Website.MaterialesService.Paginacion paginacion) {
            return base.Channel.ObtenerMaterialesPaginados(paginacion);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.MaterialesService.ListasServicioOfMaterialesModelLLZUzu_Sn> ObtenerMaterialesPaginadosAsync(EMI.Website.MaterialesService.Paginacion paginacion) {
            return base.Channel.ObtenerMaterialesPaginadosAsync(paginacion);
        }
        
        public EMI.Website.MaterialesService.MATERIALES_BELICOS ObtenerMaterialBelico(int ID) {
            return base.Channel.ObtenerMaterialBelico(ID);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.MaterialesService.MATERIALES_BELICOS> ObtenerMaterialBelicoAsync(int ID) {
            return base.Channel.ObtenerMaterialBelicoAsync(ID);
        }
    }
}
