Ext.define('App.Model.OrdenesTrabajo.DetalleTrabajosEjecutados', {
    extend: 'Ext.data.Model',
    idProperty: 'ID_TE_DET',
    fields: [
              { name: 'ID_TE_DET', type: 'int' },
              { name: 'ID_TE', type: 'int', useNull: true },
              { name: 'ID_OT', type: 'int', useNull: true },
              { name: 'OT_ORIGEN', type: 'int', useNull: true },
              { name: 'OBJETO' },
              { name: 'ID_POSTE', type: 'int', useNull: true },
              { name: 'COD_POSTE', type: 'string' },
              { name: 'ID_CONDUCTOR', type: 'int', useNull: true },
              { name: 'COD_CONDUCTOR', type: 'string' },
              { name: 'FORMACION_CND' },
              { name: 'ID_UC', type: 'int', useNull: true },
              { name: 'CODIGO_UC' },
              { name: 'ID_COD_MAN', type: 'int', useNull: true },
              { name: 'COD_MAN' },
              { name: 'ID_COD_SOL', type: 'int', useNull: true },
              { name: 'COD_SOL' },
              { name: 'IDPRODUCTO', type: 'int', useNull: true },
              { name: 'COD_PROD' },
              { name: 'DESC_PROD' },
              { name: 'UNID_PROD' },
              { name: 'CANT_PRE', type: 'int' },
              { name: 'CANT_EJE', type: 'int' },
              { name: 'FECHA_EJE_INI', type: 'date' },
              { name: 'FCH_HOR_INI', type: 'date' },
              { name: 'HORA_INI'},
              { name: 'FCH_HOR_FIN', type: 'date', dateParamFormat: 'd/m/Y H:i' },
              { name: 'HORA_FIN' },
              { name: 'ID_RESP', type: 'int', useNull: true },
              { name: 'CAPATAZ' },
              { name: 'ID_MOVIL', type: 'int', useNull: true },
              { name: 'MOVIL' },
              { name: 'NIVEL', type: 'int' },
              { name: 'OBSERVACION' },
              { name: 'CODIGO', type: 'string' },
              { name: 'TIPO_PROD'},
              { name: 'COSTO_UNIT', type: 'decimal' },
              { name: 'DISTANCIA', type: 'int' },
              { name: 'EMERGENCIA' },
              { name: 'TERR_DURO' },
              { name: 'ESTADO_TERR' },
              { name: 'DOMINGO' },
              { name: 'NUEVA_INSTAL' },
              { name: 'NUMERO_OA', type: 'int' },
              { name: 'OTRAS_PLACAS' },
              { name: 'ESTADO_PLACA' },
              { name: 'AP' }
    ],

    validations: [
        { type: 'presence', field: 'NIVEL', message: 'Introduzca el NIVEL de la estructura' }
    ]
});