Ext.define('App.Model.OrdenesTrabajo.DetallesPlanilla', {
    extend: 'Ext.data.Model',
    fields: [
        { type: "int", name: "ID_PLA_DET" },
        { type: "int", name: "ID_PLA" },
        //{ type: "string", name: "COD_POSTE" },
        { type: "string", name: "CODIGO" },
        { type: "string", name: "COD_UC" },
        { type: "string", name: "TENSION" },
        { type: "string", name: "COD_MAN" },
        { type: "string", name: "COD_SOL" },
        { type: "string", name: "DESCRIPCION" },
        { type: "int", name: "PIQUETE" },
        { type: "int", name: "ID_POSTE" },
        { type: "int", name: "ID_CONDUCTOR" },
        { type: "int", name: "ID_UC" },
        { type: "int", name: "ID_COD_MAN" },
        { type: "int", name: "ID_COD_SOL" },
        { type: "string", name: "FORMACION_CND" },
        { type: "int", name: "NIVEL" },
        { type: "int", name: "CANTIDAD" },
        { type: "string", name: "AP" },
        { type: "int", name: "DIST_POS_CAMI" },
        { type: "int", name: "CANT_ACOM" },
        { type: "string", name: "OBSERV" },
        { type: "int", name: "IDPRODUCTO" },
        { type: "string", name: "COD_PROD" },
        { type: "string", name: "DESC_PROD" },
        { type: "string", name: "UNID_PROD" },
        { type: "float", name: "CANT_PRE" },
    ]
});