//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.ListaService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _dcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _dc {
            get {
                return this._dcField;
            }
            set {
                if ((this._dcField.Equals(value) != true)) {
                    this._dcField = value;
                    this.RaisePropertyChanged("_dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                if ((this.limitField.Equals(value) != true)) {
                    this.limitField = value;
                    this.RaisePropertyChanged("limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                if ((object.ReferenceEquals(this.sortField, value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosModelOfListasItemsModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class FiltrosModelOfListasItemsModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComparadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DiccionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.ListasItemsModel EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EstadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_FINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_INICIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comparador {
            get {
                return this.ComparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComparadorField, value) != true)) {
                    this.ComparadorField = value;
                    this.RaisePropertyChanged("Comparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Diccionario {
            get {
                return this.DiccionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioField, value) != true)) {
                    this.DiccionarioField = value;
                    this.RaisePropertyChanged("Diccionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.ListasItemsModel Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Estados {
            get {
                return this.EstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadosField, value) != true)) {
                    this.EstadosField = value;
                    this.RaisePropertyChanged("Estados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_FINAL {
            get {
                return this.FECHA_FINALField;
            }
            set {
                if ((this.FECHA_FINALField.Equals(value) != true)) {
                    this.FECHA_FINALField = value;
                    this.RaisePropertyChanged("FECHA_FINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_INICIAL {
            get {
                return this.FECHA_INICIALField;
            }
            set {
                if ((this.FECHA_INICIALField.Equals(value) != true)) {
                    this.FECHA_INICIALField = value;
                    this.RaisePropertyChanged("FECHA_INICIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Predicado {
            get {
                return this.PredicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PredicadoField, value) != true)) {
                    this.PredicadoField = value;
                    this.RaisePropertyChanged("Predicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unidades {
            get {
                return this.UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesField, value) != true)) {
                    this.UnidadesField = value;
                    this.RaisePropertyChanged("Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasItemsModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasItemsModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_LISTA {
            get {
                return this.ID_LISTAField;
            }
            set {
                if ((this.ID_LISTAField.Equals(value) != true)) {
                    this.ID_LISTAField = value;
                    this.RaisePropertyChanged("ID_LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_PADRE {
            get {
                return this.ID_PADREField;
            }
            set {
                if ((this.ID_PADREField.Equals(value) != true)) {
                    this.ID_PADREField = value;
                    this.RaisePropertyChanged("ID_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_TABLA {
            get {
                return this.ID_TABLAField;
            }
            set {
                if ((this.ID_TABLAField.Equals(value) != true)) {
                    this.ID_TABLAField = value;
                    this.RaisePropertyChanged("ID_TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORField, value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfListasItemsModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfListasItemsModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.ListasItemsModel[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.ListasItemsModel[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosModelOfListasModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class FiltrosModelOfListasModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComparadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DiccionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.ListasModel EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EstadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_FINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_INICIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comparador {
            get {
                return this.ComparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComparadorField, value) != true)) {
                    this.ComparadorField = value;
                    this.RaisePropertyChanged("Comparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Diccionario {
            get {
                return this.DiccionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioField, value) != true)) {
                    this.DiccionarioField = value;
                    this.RaisePropertyChanged("Diccionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.ListasModel Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Estados {
            get {
                return this.EstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadosField, value) != true)) {
                    this.EstadosField = value;
                    this.RaisePropertyChanged("Estados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_FINAL {
            get {
                return this.FECHA_FINALField;
            }
            set {
                if ((this.FECHA_FINALField.Equals(value) != true)) {
                    this.FECHA_FINALField = value;
                    this.RaisePropertyChanged("FECHA_FINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_INICIAL {
            get {
                return this.FECHA_INICIALField;
            }
            set {
                if ((this.FECHA_INICIALField.Equals(value) != true)) {
                    this.FECHA_INICIALField = value;
                    this.RaisePropertyChanged("FECHA_INICIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Predicado {
            get {
                return this.PredicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PredicadoField, value) != true)) {
                    this.PredicadoField = value;
                    this.RaisePropertyChanged("Predicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unidades {
            get {
                return this.UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesField, value) != true)) {
                    this.UnidadesField = value;
                    this.RaisePropertyChanged("Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAYUS_MINUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<short> TAM_LIMITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_LISTA {
            get {
                return this.ID_LISTAField;
            }
            set {
                if ((this.ID_LISTAField.Equals(value) != true)) {
                    this.ID_LISTAField = value;
                    this.RaisePropertyChanged("ID_LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LISTA {
            get {
                return this.LISTAField;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAField, value) != true)) {
                    this.LISTAField = value;
                    this.RaisePropertyChanged("LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAYUS_MINUS {
            get {
                return this.MAYUS_MINUSField;
            }
            set {
                if ((object.ReferenceEquals(this.MAYUS_MINUSField, value) != true)) {
                    this.MAYUS_MINUSField = value;
                    this.RaisePropertyChanged("MAYUS_MINUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<short> TAM_LIMITE {
            get {
                return this.TAM_LIMITEField;
            }
            set {
                if ((this.TAM_LIMITEField.Equals(value) != true)) {
                    this.TAM_LIMITEField = value;
                    this.RaisePropertyChanged("TAM_LIMITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_VALOR {
            get {
                return this.TIPO_VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_VALORField, value) != true)) {
                    this.TIPO_VALORField = value;
                    this.RaisePropertyChanged("TIPO_VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfListasModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfListasModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.ListasModel[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.ListasModel[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicio", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LISTAS1", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Model")]
    [System.SerializableAttribute()]
    public partial class LISTAS1 : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DESCRIPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.LISTAS_ITEMS[] LISTAS_ITEMSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MAYUS_MINUSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int TAM_LIMITEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION {
            get {
                return this.DESCRIPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.DESCRIPCIONField, value) != true)) {
                    this.DESCRIPCIONField = value;
                    this.RaisePropertyChanged("DESCRIPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LISTA {
            get {
                return this.ID_LISTAField;
            }
            set {
                if ((this.ID_LISTAField.Equals(value) != true)) {
                    this.ID_LISTAField = value;
                    this.RaisePropertyChanged("ID_LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LISTA {
            get {
                return this.LISTAField;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAField, value) != true)) {
                    this.LISTAField = value;
                    this.RaisePropertyChanged("LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.LISTAS_ITEMS[] LISTAS_ITEMS {
            get {
                return this.LISTAS_ITEMSField;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAS_ITEMSField, value) != true)) {
                    this.LISTAS_ITEMSField = value;
                    this.RaisePropertyChanged("LISTAS_ITEMS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MAYUS_MINUS {
            get {
                return this.MAYUS_MINUSField;
            }
            set {
                if ((object.ReferenceEquals(this.MAYUS_MINUSField, value) != true)) {
                    this.MAYUS_MINUSField = value;
                    this.RaisePropertyChanged("MAYUS_MINUS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TAM_LIMITE {
            get {
                return this.TAM_LIMITEField;
            }
            set {
                if ((this.TAM_LIMITEField.Equals(value) != true)) {
                    this.TAM_LIMITEField = value;
                    this.RaisePropertyChanged("TAM_LIMITE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_VALOR {
            get {
                return this.TIPO_VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_VALORField, value) != true)) {
                    this.TIPO_VALORField = value;
                    this.RaisePropertyChanged("TIPO_VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LISTAS_ITEMS", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Model")]
    [System.SerializableAttribute()]
    public partial class LISTAS_ITEMS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_LISTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.LISTAS1 LISTAS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.LISTAS_ITEMS[] LISTAS_ITEMS1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.ListaService.LISTAS_ITEMS LISTAS_ITEMS2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_LISTA {
            get {
                return this.ID_LISTAField;
            }
            set {
                if ((this.ID_LISTAField.Equals(value) != true)) {
                    this.ID_LISTAField = value;
                    this.RaisePropertyChanged("ID_LISTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_PADRE {
            get {
                return this.ID_PADREField;
            }
            set {
                if ((this.ID_PADREField.Equals(value) != true)) {
                    this.ID_PADREField = value;
                    this.RaisePropertyChanged("ID_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_TABLA {
            get {
                return this.ID_TABLAField;
            }
            set {
                if ((this.ID_TABLAField.Equals(value) != true)) {
                    this.ID_TABLAField = value;
                    this.RaisePropertyChanged("ID_TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.LISTAS1 LISTAS1 {
            get {
                return this.LISTAS1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAS1Field, value) != true)) {
                    this.LISTAS1Field = value;
                    this.RaisePropertyChanged("LISTAS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.LISTAS_ITEMS[] LISTAS_ITEMS1 {
            get {
                return this.LISTAS_ITEMS1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAS_ITEMS1Field, value) != true)) {
                    this.LISTAS_ITEMS1Field = value;
                    this.RaisePropertyChanged("LISTAS_ITEMS1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.ListaService.LISTAS_ITEMS LISTAS_ITEMS2 {
            get {
                return this.LISTAS_ITEMS2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LISTAS_ITEMS2Field, value) != true)) {
                    this.LISTAS_ITEMS2Field = value;
                    this.RaisePropertyChanged("LISTAS_ITEMS2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORField, value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ListaService.IListas")]
    public interface IListas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerListasItems", ReplyAction="http://tempuri.org/IListas/ObtenerListasItemsResponse")]
        EMI.Website.ListaService.ListasServicioOfListasItemsModelRb2EILji ObtenerListasItems(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasItemsModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerListasItems", ReplyAction="http://tempuri.org/IListas/ObtenerListasItemsResponse")]
        System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasItemsModelRb2EILji> ObtenerListasItemsAsync(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasItemsModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerListas", ReplyAction="http://tempuri.org/IListas/ObtenerListasResponse")]
        EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji ObtenerListas(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerListas", ReplyAction="http://tempuri.org/IListas/ObtenerListasResponse")]
        System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji> ObtenerListasAsync(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerTodasListas", ReplyAction="http://tempuri.org/IListas/ObtenerTodasListasResponse")]
        EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji ObtenerTodasListas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/ObtenerTodasListas", ReplyAction="http://tempuri.org/IListas/ObtenerTodasListasResponse")]
        System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji> ObtenerTodasListasAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/GuardarLista", ReplyAction="http://tempuri.org/IListas/GuardarListaResponse")]
        EMI.Website.ListaService.RespuestaServicio GuardarLista(EMI.Website.ListaService.LISTAS1 lista, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/GuardarLista", ReplyAction="http://tempuri.org/IListas/GuardarListaResponse")]
        System.Threading.Tasks.Task<EMI.Website.ListaService.RespuestaServicio> GuardarListaAsync(EMI.Website.ListaService.LISTAS1 lista, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/GuardarItemLista", ReplyAction="http://tempuri.org/IListas/GuardarItemListaResponse")]
        EMI.Website.ListaService.RespuestaServicio GuardarItemLista(EMI.Website.ListaService.LISTAS_ITEMS lista, string usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListas/GuardarItemLista", ReplyAction="http://tempuri.org/IListas/GuardarItemListaResponse")]
        System.Threading.Tasks.Task<EMI.Website.ListaService.RespuestaServicio> GuardarItemListaAsync(EMI.Website.ListaService.LISTAS_ITEMS lista, string usuario);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IListasChannel : EMI.Website.ListaService.IListas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ListasClient : System.ServiceModel.ClientBase<EMI.Website.ListaService.IListas>, EMI.Website.ListaService.IListas {
        
        public ListasClient() {
        }
        
        public ListasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ListasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ListasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.ListaService.ListasServicioOfListasItemsModelRb2EILji ObtenerListasItems(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasItemsModelRb2EILji filtros) {
            return base.Channel.ObtenerListasItems(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasItemsModelRb2EILji> ObtenerListasItemsAsync(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasItemsModelRb2EILji filtros) {
            return base.Channel.ObtenerListasItemsAsync(paginacion, filtros);
        }
        
        public EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji ObtenerListas(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasModelRb2EILji filtros) {
            return base.Channel.ObtenerListas(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji> ObtenerListasAsync(EMI.Website.ListaService.Paginacion paginacion, EMI.Website.ListaService.FiltrosModelOfListasModelRb2EILji filtros) {
            return base.Channel.ObtenerListasAsync(paginacion, filtros);
        }
        
        public EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji ObtenerTodasListas() {
            return base.Channel.ObtenerTodasListas();
        }
        
        public System.Threading.Tasks.Task<EMI.Website.ListaService.ListasServicioOfListasModelRb2EILji> ObtenerTodasListasAsync() {
            return base.Channel.ObtenerTodasListasAsync();
        }
        
        public EMI.Website.ListaService.RespuestaServicio GuardarLista(EMI.Website.ListaService.LISTAS1 lista, string usuario) {
            return base.Channel.GuardarLista(lista, usuario);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.ListaService.RespuestaServicio> GuardarListaAsync(EMI.Website.ListaService.LISTAS1 lista, string usuario) {
            return base.Channel.GuardarListaAsync(lista, usuario);
        }
        
        public EMI.Website.ListaService.RespuestaServicio GuardarItemLista(EMI.Website.ListaService.LISTAS_ITEMS lista, string usuario) {
            return base.Channel.GuardarItemLista(lista, usuario);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.ListaService.RespuestaServicio> GuardarItemListaAsync(EMI.Website.ListaService.LISTAS_ITEMS lista, string usuario) {
            return base.Channel.GuardarItemListaAsync(lista, usuario);
        }
    }
}
