//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.KardexMunicionesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _dcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _dc {
            get {
                return this._dcField;
            }
            set {
                if ((this._dcField.Equals(value) != true)) {
                    this._dcField = value;
                    this.RaisePropertyChanged("_dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                if ((this.limitField.Equals(value) != true)) {
                    this.limitField = value;
                    this.RaisePropertyChanged("limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                if ((object.ReferenceEquals(this.sortField, value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosModelOfKardexModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class FiltrosModelOfKardexModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComparadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DiccionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.KardexMunicionesService.KardexModel EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EstadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_FINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_INICIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comparador {
            get {
                return this.ComparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComparadorField, value) != true)) {
                    this.ComparadorField = value;
                    this.RaisePropertyChanged("Comparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Diccionario {
            get {
                return this.DiccionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioField, value) != true)) {
                    this.DiccionarioField = value;
                    this.RaisePropertyChanged("Diccionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.KardexMunicionesService.KardexModel Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Estados {
            get {
                return this.EstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadosField, value) != true)) {
                    this.EstadosField = value;
                    this.RaisePropertyChanged("Estados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_FINAL {
            get {
                return this.FECHA_FINALField;
            }
            set {
                if ((this.FECHA_FINALField.Equals(value) != true)) {
                    this.FECHA_FINALField = value;
                    this.RaisePropertyChanged("FECHA_FINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_INICIAL {
            get {
                return this.FECHA_INICIALField;
            }
            set {
                if ((this.FECHA_INICIALField.Equals(value) != true)) {
                    this.FECHA_INICIALField = value;
                    this.RaisePropertyChanged("FECHA_INICIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Predicado {
            get {
                return this.PredicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PredicadoField, value) != true)) {
                    this.PredicadoField = value;
                    this.RaisePropertyChanged("Predicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unidades {
            get {
                return this.UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesField, value) != true)) {
                    this.UnidadesField = value;
                    this.RaisePropertyChanged("Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KardexModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class KardexModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_ITEM_NO_OPERABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_ITEM_OPERABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MAT_BELICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MUNICION_UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_ITEM_NO_OPERABLE {
            get {
                return this.ID_ITEM_NO_OPERABLEField;
            }
            set {
                if ((this.ID_ITEM_NO_OPERABLEField.Equals(value) != true)) {
                    this.ID_ITEM_NO_OPERABLEField = value;
                    this.RaisePropertyChanged("ID_ITEM_NO_OPERABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_ITEM_OPERABLE {
            get {
                return this.ID_ITEM_OPERABLEField;
            }
            set {
                if ((this.ID_ITEM_OPERABLEField.Equals(value) != true)) {
                    this.ID_ITEM_OPERABLEField = value;
                    this.RaisePropertyChanged("ID_ITEM_OPERABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MAT_BELICO {
            get {
                return this.ID_MAT_BELICOField;
            }
            set {
                if ((this.ID_MAT_BELICOField.Equals(value) != true)) {
                    this.ID_MAT_BELICOField = value;
                    this.RaisePropertyChanged("ID_MAT_BELICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MUNICION_UNIDAD {
            get {
                return this.ID_MUNICION_UNIDADField;
            }
            set {
                if ((this.ID_MUNICION_UNIDADField.Equals(value) != true)) {
                    this.ID_MUNICION_UNIDADField = value;
                    this.RaisePropertyChanged("ID_MUNICION_UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KardexModelResp", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class KardexModelResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ENTRADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MAT_BELICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MOVField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MUNICION_UNIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_OPERACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OPERACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SALDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SALIDAField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ENTRADA {
            get {
                return this.ENTRADAField;
            }
            set {
                if ((this.ENTRADAField.Equals(value) != true)) {
                    this.ENTRADAField = value;
                    this.RaisePropertyChanged("ENTRADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MAT_BELICO {
            get {
                return this.ID_MAT_BELICOField;
            }
            set {
                if ((this.ID_MAT_BELICOField.Equals(value) != true)) {
                    this.ID_MAT_BELICOField = value;
                    this.RaisePropertyChanged("ID_MAT_BELICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MOV {
            get {
                return this.ID_MOVField;
            }
            set {
                if ((this.ID_MOVField.Equals(value) != true)) {
                    this.ID_MOVField = value;
                    this.RaisePropertyChanged("ID_MOV");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MUNICION_UNIDAD {
            get {
                return this.ID_MUNICION_UNIDADField;
            }
            set {
                if ((this.ID_MUNICION_UNIDADField.Equals(value) != true)) {
                    this.ID_MUNICION_UNIDADField = value;
                    this.RaisePropertyChanged("ID_MUNICION_UNIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_OPERACION {
            get {
                return this.ID_OPERACIONField;
            }
            set {
                if ((this.ID_OPERACIONField.Equals(value) != true)) {
                    this.ID_OPERACIONField = value;
                    this.RaisePropertyChanged("ID_OPERACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OPERACION {
            get {
                return this.OPERACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OPERACIONField, value) != true)) {
                    this.OPERACIONField = value;
                    this.RaisePropertyChanged("OPERACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SALDO {
            get {
                return this.SALDOField;
            }
            set {
                if ((this.SALDOField.Equals(value) != true)) {
                    this.SALDOField = value;
                    this.RaisePropertyChanged("SALDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SALIDA {
            get {
                return this.SALIDAField;
            }
            set {
                if ((this.SALIDAField.Equals(value) != true)) {
                    this.SALIDAField = value;
                    this.RaisePropertyChanged("SALIDA");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ArmamentoModelResp", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class ArmamentoModelResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CALIBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANTIDAD_DISPONIBLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FABRICACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_BAJAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_DOTACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MAT_BELICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGIN_BAJAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_CANONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_CIERREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_CORREDERAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_FUSILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACION_BAJAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CALIBRE {
            get {
                return this.CALIBREField;
            }
            set {
                if ((object.ReferenceEquals(this.CALIBREField, value) != true)) {
                    this.CALIBREField = value;
                    this.RaisePropertyChanged("CALIBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANTIDAD_DISPONIBLE {
            get {
                return this.CANTIDAD_DISPONIBLEField;
            }
            set {
                if ((this.CANTIDAD_DISPONIBLEField.Equals(value) != true)) {
                    this.CANTIDAD_DISPONIBLEField = value;
                    this.RaisePropertyChanged("CANTIDAD_DISPONIBLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORIA {
            get {
                return this.CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIAField, value) != true)) {
                    this.CATEGORIAField = value;
                    this.RaisePropertyChanged("CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FABRICACION {
            get {
                return this.FABRICACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.FABRICACIONField, value) != true)) {
                    this.FABRICACIONField = value;
                    this.RaisePropertyChanged("FABRICACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_BAJA {
            get {
                return this.FECHA_BAJAField;
            }
            set {
                if ((this.FECHA_BAJAField.Equals(value) != true)) {
                    this.FECHA_BAJAField = value;
                    this.RaisePropertyChanged("FECHA_BAJA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_DOTACION {
            get {
                return this.FECHA_DOTACIONField;
            }
            set {
                if ((this.FECHA_DOTACIONField.Equals(value) != true)) {
                    this.FECHA_DOTACIONField = value;
                    this.RaisePropertyChanged("FECHA_DOTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ITEM {
            get {
                return this.ID_ITEMField;
            }
            set {
                if ((this.ID_ITEMField.Equals(value) != true)) {
                    this.ID_ITEMField = value;
                    this.RaisePropertyChanged("ID_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MAT_BELICO {
            get {
                return this.ID_MAT_BELICOField;
            }
            set {
                if ((this.ID_MAT_BELICOField.Equals(value) != true)) {
                    this.ID_MAT_BELICOField = value;
                    this.RaisePropertyChanged("ID_MAT_BELICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN_BAJA {
            get {
                return this.LOGIN_BAJAField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGIN_BAJAField, value) != true)) {
                    this.LOGIN_BAJAField = value;
                    this.RaisePropertyChanged("LOGIN_BAJA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_CANON {
            get {
                return this.NRO_CANONField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_CANONField, value) != true)) {
                    this.NRO_CANONField = value;
                    this.RaisePropertyChanged("NRO_CANON");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_CIERRE {
            get {
                return this.NRO_CIERREField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_CIERREField, value) != true)) {
                    this.NRO_CIERREField = value;
                    this.RaisePropertyChanged("NRO_CIERRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_CORREDERA {
            get {
                return this.NRO_CORREDERAField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_CORREDERAField, value) != true)) {
                    this.NRO_CORREDERAField = value;
                    this.RaisePropertyChanged("NRO_CORREDERA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_FUSIL {
            get {
                return this.NRO_FUSILField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_FUSILField, value) != true)) {
                    this.NRO_FUSILField = value;
                    this.RaisePropertyChanged("NRO_FUSIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACION {
            get {
                return this.OBSERVACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONField, value) != true)) {
                    this.OBSERVACIONField = value;
                    this.RaisePropertyChanged("OBSERVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACION_BAJA {
            get {
                return this.OBSERVACION_BAJAField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACION_BAJAField, value) != true)) {
                    this.OBSERVACION_BAJAField = value;
                    this.RaisePropertyChanged("OBSERVACION_BAJA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO {
            get {
                return this.TIPOField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPOField, value) != true)) {
                    this.TIPOField = value;
                    this.RaisePropertyChanged("TIPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDAD {
            get {
                return this.UNIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADField, value) != true)) {
                    this.UNIDADField = value;
                    this.RaisePropertyChanged("UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfKardexModelRespLLZUzu_Sn", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfKardexModelRespLLZUzu_Sn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.KardexMunicionesService.KardexModelResp[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.KardexMunicionesService.KardexModelResp[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfArmamentoModelRespLLZUzu_Sn", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfArmamentoModelRespLLZUzu_Sn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.KardexMunicionesService.ArmamentoModelResp[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.KardexMunicionesService.ArmamentoModelResp[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="KardexMunicionesService.IKardexMuniciones")]
    public interface IKardexMuniciones {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerKardexUnidadPaginados", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerKardexUnidadPaginadosResponse")]
        EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn ObtenerKardexUnidadPaginados(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerKardexUnidadPaginados", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerKardexUnidadPaginadosResponse")]
        System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn> ObtenerKardexUnidadPaginadosAsync(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerKardexPaginados", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerKardexPaginadosResponse")]
        EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn ObtenerKardexPaginados(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerKardexPaginados", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerKardexPaginadosResponse")]
        System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn> ObtenerKardexPaginadosAsync(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerMoviminetosMunicionUnidad", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerMoviminetosMunicionUnidadResponse")]
        EMI.Website.KardexMunicionesService.ListasServicioOfArmamentoModelRespLLZUzu_Sn ObtenerMoviminetosMunicionUnidad(int ID_MUNICION_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IKardexMuniciones/ObtenerMoviminetosMunicionUnidad", ReplyAction="http://tempuri.org/IKardexMuniciones/ObtenerMoviminetosMunicionUnidadResponse")]
        System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfArmamentoModelRespLLZUzu_Sn> ObtenerMoviminetosMunicionUnidadAsync(int ID_MUNICION_UNIDAD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IKardexMunicionesChannel : EMI.Website.KardexMunicionesService.IKardexMuniciones, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class KardexMunicionesClient : System.ServiceModel.ClientBase<EMI.Website.KardexMunicionesService.IKardexMuniciones>, EMI.Website.KardexMunicionesService.IKardexMuniciones {
        
        public KardexMunicionesClient() {
        }
        
        public KardexMunicionesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public KardexMunicionesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KardexMunicionesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public KardexMunicionesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn ObtenerKardexUnidadPaginados(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerKardexUnidadPaginados(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn> ObtenerKardexUnidadPaginadosAsync(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerKardexUnidadPaginadosAsync(paginacion, filtros);
        }
        
        public EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn ObtenerKardexPaginados(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerKardexPaginados(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfKardexModelRespLLZUzu_Sn> ObtenerKardexPaginadosAsync(EMI.Website.KardexMunicionesService.Paginacion paginacion, EMI.Website.KardexMunicionesService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerKardexPaginadosAsync(paginacion, filtros);
        }
        
        public EMI.Website.KardexMunicionesService.ListasServicioOfArmamentoModelRespLLZUzu_Sn ObtenerMoviminetosMunicionUnidad(int ID_MUNICION_UNIDAD) {
            return base.Channel.ObtenerMoviminetosMunicionUnidad(ID_MUNICION_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.KardexMunicionesService.ListasServicioOfArmamentoModelRespLLZUzu_Sn> ObtenerMoviminetosMunicionUnidadAsync(int ID_MUNICION_UNIDAD) {
            return base.Channel.ObtenerMoviminetosMunicionUnidadAsync(ID_MUNICION_UNIDAD);
        }
    }
}
