//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.BitacorasService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _dcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _dc {
            get {
                return this._dcField;
            }
            set {
                if ((this._dcField.Equals(value) != true)) {
                    this._dcField = value;
                    this.RaisePropertyChanged("_dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                if ((this.limitField.Equals(value) != true)) {
                    this.limitField = value;
                    this.RaisePropertyChanged("limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                if ((object.ReferenceEquals(this.sortField, value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosModelOfBitacorasModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class FiltrosModelOfBitacorasModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComparadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DiccionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.BitacorasService.BitacorasModel EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EstadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_FINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_INICIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comparador {
            get {
                return this.ComparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComparadorField, value) != true)) {
                    this.ComparadorField = value;
                    this.RaisePropertyChanged("Comparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Diccionario {
            get {
                return this.DiccionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioField, value) != true)) {
                    this.DiccionarioField = value;
                    this.RaisePropertyChanged("Diccionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.BitacorasService.BitacorasModel Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Estados {
            get {
                return this.EstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadosField, value) != true)) {
                    this.EstadosField = value;
                    this.RaisePropertyChanged("Estados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_FINAL {
            get {
                return this.FECHA_FINALField;
            }
            set {
                if ((this.FECHA_FINALField.Equals(value) != true)) {
                    this.FECHA_FINALField = value;
                    this.RaisePropertyChanged("FECHA_FINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_INICIAL {
            get {
                return this.FECHA_INICIALField;
            }
            set {
                if ((this.FECHA_INICIALField.Equals(value) != true)) {
                    this.FECHA_INICIALField = value;
                    this.RaisePropertyChanged("FECHA_INICIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Predicado {
            get {
                return this.PredicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PredicadoField, value) != true)) {
                    this.PredicadoField = value;
                    this.RaisePropertyChanged("Predicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unidades {
            get {
                return this.UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesField, value) != true)) {
                    this.UnidadesField = value;
                    this.RaisePropertyChanged("Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BitacorasModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class BitacorasModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ACCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COLUMNAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ID_HISTField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<long> ID_TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string VALORField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ACCION {
            get {
                return this.ACCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ACCIONField, value) != true)) {
                    this.ACCIONField = value;
                    this.RaisePropertyChanged("ACCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COLUMNA {
            get {
                return this.COLUMNAField;
            }
            set {
                if ((object.ReferenceEquals(this.COLUMNAField, value) != true)) {
                    this.COLUMNAField = value;
                    this.RaisePropertyChanged("COLUMNA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID_HIST {
            get {
                return this.ID_HISTField;
            }
            set {
                if ((this.ID_HISTField.Equals(value) != true)) {
                    this.ID_HISTField = value;
                    this.RaisePropertyChanged("ID_HIST");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<long> ID_TABLA {
            get {
                return this.ID_TABLAField;
            }
            set {
                if ((this.ID_TABLAField.Equals(value) != true)) {
                    this.ID_TABLAField = value;
                    this.RaisePropertyChanged("ID_TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TABLA {
            get {
                return this.TABLAField;
            }
            set {
                if ((object.ReferenceEquals(this.TABLAField, value) != true)) {
                    this.TABLAField = value;
                    this.RaisePropertyChanged("TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string VALOR {
            get {
                return this.VALORField;
            }
            set {
                if ((object.ReferenceEquals(this.VALORField, value) != true)) {
                    this.VALORField = value;
                    this.RaisePropertyChanged("VALOR");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricoEdicionModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class HistoricoEdicionModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MOTIVOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TABLAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USUARIOField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DETALLE {
            get {
                return this.DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLEField, value) != true)) {
                    this.DETALLEField = value;
                    this.RaisePropertyChanged("DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MOTIVO {
            get {
                return this.MOTIVOField;
            }
            set {
                if ((object.ReferenceEquals(this.MOTIVOField, value) != true)) {
                    this.MOTIVOField = value;
                    this.RaisePropertyChanged("MOTIVO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TABLA {
            get {
                return this.TABLAField;
            }
            set {
                if ((object.ReferenceEquals(this.TABLAField, value) != true)) {
                    this.TABLAField = value;
                    this.RaisePropertyChanged("TABLA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USUARIO {
            get {
                return this.USUARIOField;
            }
            set {
                if ((object.ReferenceEquals(this.USUARIOField, value) != true)) {
                    this.USUARIOField = value;
                    this.RaisePropertyChanged("USUARIO");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BitacorasService.IBitacoras")]
    public interface IBitacoras {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoras/ObtenerBitacoras", ReplyAction="http://tempuri.org/IBitacoras/ObtenerBitacorasResponse")]
        EMI.Website.BitacorasService.HistoricoEdicionModel[] ObtenerBitacoras(EMI.Website.BitacorasService.Paginacion paginacion, EMI.Website.BitacorasService.FiltrosModelOfBitacorasModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBitacoras/ObtenerBitacoras", ReplyAction="http://tempuri.org/IBitacoras/ObtenerBitacorasResponse")]
        System.Threading.Tasks.Task<EMI.Website.BitacorasService.HistoricoEdicionModel[]> ObtenerBitacorasAsync(EMI.Website.BitacorasService.Paginacion paginacion, EMI.Website.BitacorasService.FiltrosModelOfBitacorasModelRb2EILji filtros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBitacorasChannel : EMI.Website.BitacorasService.IBitacoras, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BitacorasClient : System.ServiceModel.ClientBase<EMI.Website.BitacorasService.IBitacoras>, EMI.Website.BitacorasService.IBitacoras {
        
        public BitacorasClient() {
        }
        
        public BitacorasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BitacorasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacorasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BitacorasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.BitacorasService.HistoricoEdicionModel[] ObtenerBitacoras(EMI.Website.BitacorasService.Paginacion paginacion, EMI.Website.BitacorasService.FiltrosModelOfBitacorasModelRb2EILji filtros) {
            return base.Channel.ObtenerBitacoras(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.BitacorasService.HistoricoEdicionModel[]> ObtenerBitacorasAsync(EMI.Website.BitacorasService.Paginacion paginacion, EMI.Website.BitacorasService.FiltrosModelOfBitacorasModelRb2EILji filtros) {
            return base.Channel.ObtenerBitacorasAsync(paginacion, filtros);
        }
    }
}
