Ext.define('App.Model.OrdenesOperacion.OrdenesOperacion', {
    extend: 'Ext.data.Model',
    fields: [
            { type: "int", name: "ID_OT" },
            { type: 'int', name: 'ID_OT1', defaultValue: 'ID_OT', convert: Funciones.CopiarRecordmodelo },
            { type: "int", name: "ID_SOL_MAN" },
            { type: "int", name: "ID_OO" },
            { type: 'int', name: 'NRO_SOL', defaultValue: 'ID_SOL_MAN', convert: Funciones.CopiarRecordmodelo },
            { type: 'int', name: 'NRO_OO'},
            { type: "string", name: "OPERACION" },
            { type: "string", name: "TIPO_FAENA" },
            { type: "string", name: "SOLICITADO_POR" },
            { type: "string", name: "TRABAJO_REALIZAR" },
            { type: "string", name: "INSTAL_INTERV" },
            { type: "int", name: "ID_SUBEST" },
            { type: "string", name: "NOM_SUBEST" },
            { type: "int", name: "ID_LINEA" },
            { type: "string", name: "COD_LINEA" },
            { type: "int", name: "ID_ALIMENTADOR" },
            { type: "string", name: "COD_ALIMENTADOR" },
            { type: "string", name: "TIPO_DERIVACION" },
            { type: "string", name: "TIPO_EQUIPO" },
            { type: "int", name: "ID_DERIVACION" },
            { type: "string", name: "COD_DERIVACION" },
            { type: "string", name: "EQUIPO_1" },
            { type: "string", name: "EQUIPO_2" },
            { type: "string", name: "EQUIPO_3" },
            { type: "int", name: "ID_PUESTO" },
            { type: "string", name: "COD_PUESTO" },
            { type: "string", name: "OTRAS_INSTAL" },
            { type: "date", name: "FECHA_INI", dateFormat: "d/m/Y", convert: Funciones.Fecha },
            { type: "string", name: "HORA_INI" },
            { type: "date", name: "FECHA_FIN", dateFormat: "d/m/Y", convert: Funciones.Fecha },
            { type: "string", name: "HORA_FIN" },
            { type: "string", name: "COND_OPER_REQ" },
            { type: "int", name: "ID_JEFE_FAENA" },
            { type: "int", name: "ID_BKUP_JEFE_FAENA" },
            { type: "int", name: "ID_RESP_MANIOBRA" },
            { type: "int", name: "ID_INSP_FAENA" },

            { type: "string", name: "NOMBRE_JEFEFAENA" },
            { type: "string", name: "INSPECTOR_FAENA" },
            { type: "string", name: "REEMPLAZO_JEFE_FAENA" },
            { type: "string", name: "RESPONSABLE_MANIOBRA" },

            { type: "string", name: "MEDIO_COMUNIC" },
            { type: "date", name: "FECHA_REG", dateFormat: "d/m/Y", convert: Funciones.Fecha },
            { type: "string", name: "ESTADO" },
            { type: "string", name: "LOGIN_USR" },
            { type: "string", name: "LOGIN_REG" },

             { type: "int", name: "NUMERO" },

            //MODELO DE SECUENCIA O GUIA DE MANIOBRA
            { type: "int", name: "ID_SEC" },
            { type: "int", name: "NRO_SEC" },
            { type: "string", name: "HORA" },
            { type: "string", name: "DESCRIP_MANIOBRA" },
            { type: "string", name: "CODIGO" },
            { type: "string", name: "OPERADOR" },
    ]
});