//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.AutorizacionService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaServicio", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class RespuestaServicio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int id {
            get {
                return this.idField;
            }
            set {
                if ((this.idField.Equals(value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfMenuOpcionesModelLLZUzu_Sn", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfMenuOpcionesModelLLZUzu_Sn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.AutorizacionService.MenuOpcionesModel[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.AutorizacionService.MenuOpcionesModel[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MenuOpcionesModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class MenuOpcionesModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CLASEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ICONCCSField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_MENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_PADREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MENUField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TOOLTIPField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CLASE {
            get {
                return this.CLASEField;
            }
            set {
                if ((object.ReferenceEquals(this.CLASEField, value) != true)) {
                    this.CLASEField = value;
                    this.RaisePropertyChanged("CLASE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ICONCCS {
            get {
                return this.ICONCCSField;
            }
            set {
                if ((object.ReferenceEquals(this.ICONCCSField, value) != true)) {
                    this.ICONCCSField = value;
                    this.RaisePropertyChanged("ICONCCS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_MENU {
            get {
                return this.ID_MENUField;
            }
            set {
                if ((this.ID_MENUField.Equals(value) != true)) {
                    this.ID_MENUField = value;
                    this.RaisePropertyChanged("ID_MENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_PADRE {
            get {
                return this.ID_PADREField;
            }
            set {
                if ((this.ID_PADREField.Equals(value) != true)) {
                    this.ID_PADREField = value;
                    this.RaisePropertyChanged("ID_PADRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MENU {
            get {
                return this.MENUField;
            }
            set {
                if ((object.ReferenceEquals(this.MENUField, value) != true)) {
                    this.MENUField = value;
                    this.RaisePropertyChanged("MENU");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TOOLTIP {
            get {
                return this.TOOLTIPField;
            }
            set {
                if ((object.ReferenceEquals(this.TOOLTIPField, value) != true)) {
                    this.TOOLTIPField = value;
                    this.RaisePropertyChanged("TOOLTIP");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuariosModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class UsuariosModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CONTRASEÑAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_ALTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_CADUCIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PERFILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_UNIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_USUARIOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LOGINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOMBREField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PERFILField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CONTRASEÑA {
            get {
                return this.CONTRASEÑAField;
            }
            set {
                if ((object.ReferenceEquals(this.CONTRASEÑAField, value) != true)) {
                    this.CONTRASEÑAField = value;
                    this.RaisePropertyChanged("CONTRASEÑA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_ALTA {
            get {
                return this.FECHA_ALTAField;
            }
            set {
                if ((this.FECHA_ALTAField.Equals(value) != true)) {
                    this.FECHA_ALTAField = value;
                    this.RaisePropertyChanged("FECHA_ALTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_CADUCIDAD {
            get {
                return this.FECHA_CADUCIDADField;
            }
            set {
                if ((this.FECHA_CADUCIDADField.Equals(value) != true)) {
                    this.FECHA_CADUCIDADField = value;
                    this.RaisePropertyChanged("FECHA_CADUCIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PERFIL {
            get {
                return this.ID_PERFILField;
            }
            set {
                if ((this.ID_PERFILField.Equals(value) != true)) {
                    this.ID_PERFILField = value;
                    this.RaisePropertyChanged("ID_PERFIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_UNIDAD {
            get {
                return this.ID_UNIDADField;
            }
            set {
                if ((this.ID_UNIDADField.Equals(value) != true)) {
                    this.ID_UNIDADField = value;
                    this.RaisePropertyChanged("ID_UNIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_USUARIO {
            get {
                return this.ID_USUARIOField;
            }
            set {
                if ((this.ID_USUARIOField.Equals(value) != true)) {
                    this.ID_USUARIOField = value;
                    this.RaisePropertyChanged("ID_USUARIO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LOGIN {
            get {
                return this.LOGINField;
            }
            set {
                if ((object.ReferenceEquals(this.LOGINField, value) != true)) {
                    this.LOGINField = value;
                    this.RaisePropertyChanged("LOGIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOMBRE {
            get {
                return this.NOMBREField;
            }
            set {
                if ((object.ReferenceEquals(this.NOMBREField, value) != true)) {
                    this.NOMBREField = value;
                    this.RaisePropertyChanged("NOMBRE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PERFIL {
            get {
                return this.PERFILField;
            }
            set {
                if ((object.ReferenceEquals(this.PERFILField, value) != true)) {
                    this.PERFILField = value;
                    this.RaisePropertyChanged("PERFIL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDAD {
            get {
                return this.UNIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADField, value) != true)) {
                    this.UNIDADField = value;
                    this.RaisePropertyChanged("UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AutorizacionService.IAutorizacion")]
    public interface IAutorizacion {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/VerificaUsuario", ReplyAction="http://tempuri.org/IAutorizacion/VerificaUsuarioResponse")]
        EMI.Website.AutorizacionService.RespuestaServicio VerificaUsuario(string login, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/VerificaUsuario", ReplyAction="http://tempuri.org/IAutorizacion/VerificaUsuarioResponse")]
        System.Threading.Tasks.Task<EMI.Website.AutorizacionService.RespuestaServicio> VerificaUsuarioAsync(string login, string contrasena);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/ObtenerMenuOpciones", ReplyAction="http://tempuri.org/IAutorizacion/ObtenerMenuOpcionesResponse")]
        EMI.Website.AutorizacionService.ListasServicioOfMenuOpcionesModelLLZUzu_Sn ObtenerMenuOpciones(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/ObtenerMenuOpciones", ReplyAction="http://tempuri.org/IAutorizacion/ObtenerMenuOpcionesResponse")]
        System.Threading.Tasks.Task<EMI.Website.AutorizacionService.ListasServicioOfMenuOpcionesModelLLZUzu_Sn> ObtenerMenuOpcionesAsync(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/ObtenerUsuario", ReplyAction="http://tempuri.org/IAutorizacion/ObtenerUsuarioResponse")]
        EMI.Website.AutorizacionService.UsuariosModel ObtenerUsuario(string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAutorizacion/ObtenerUsuario", ReplyAction="http://tempuri.org/IAutorizacion/ObtenerUsuarioResponse")]
        System.Threading.Tasks.Task<EMI.Website.AutorizacionService.UsuariosModel> ObtenerUsuarioAsync(string login);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutorizacionChannel : EMI.Website.AutorizacionService.IAutorizacion, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutorizacionClient : System.ServiceModel.ClientBase<EMI.Website.AutorizacionService.IAutorizacion>, EMI.Website.AutorizacionService.IAutorizacion {
        
        public AutorizacionClient() {
        }
        
        public AutorizacionClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutorizacionClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizacionClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutorizacionClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.AutorizacionService.RespuestaServicio VerificaUsuario(string login, string contrasena) {
            return base.Channel.VerificaUsuario(login, contrasena);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.AutorizacionService.RespuestaServicio> VerificaUsuarioAsync(string login, string contrasena) {
            return base.Channel.VerificaUsuarioAsync(login, contrasena);
        }
        
        public EMI.Website.AutorizacionService.ListasServicioOfMenuOpcionesModelLLZUzu_Sn ObtenerMenuOpciones(string login) {
            return base.Channel.ObtenerMenuOpciones(login);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.AutorizacionService.ListasServicioOfMenuOpcionesModelLLZUzu_Sn> ObtenerMenuOpcionesAsync(string login) {
            return base.Channel.ObtenerMenuOpcionesAsync(login);
        }
        
        public EMI.Website.AutorizacionService.UsuariosModel ObtenerUsuario(string login) {
            return base.Channel.ObtenerUsuario(login);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.AutorizacionService.UsuariosModel> ObtenerUsuarioAsync(string login) {
            return base.Channel.ObtenerUsuarioAsync(login);
        }
    }
}
