//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_LOGISTICOS
    {
        public MAT_LOGISTICOS()
        {
            this.DETALLES_PEDIDOS = new HashSet<DETALLES_PEDIDOS>();
            this.ITEMS_MAT_LOGISTICOS = new HashSet<ITEMS_MAT_LOGISTICOS>();
        }
    
        public int ID_MAT_LOGISTICO { get; set; }
        public string CODIGO { get; set; }
        public string FABRICANTE { get; set; }
        public string TIPO_COMPONENTE { get; set; }
        public string AERONAVE { get; set; }
        public string GRUPO { get; set; }
        public string NRO_PARTE { get; set; }
        public string ESTADO { get; set; }
        public Nullable<int> CICLO_VIDA { get; set; }
        public Nullable<int> HORA_VIDA { get; set; }
        public string DESCRIPCION { get; set; }
        public System.DateTime FECHA_DOTACION { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public string LOGIN { get; set; }
    
        public virtual ICollection<DETALLES_PEDIDOS> DETALLES_PEDIDOS { get; set; }
        public virtual ICollection<ITEMS_MAT_LOGISTICOS> ITEMS_MAT_LOGISTICOS { get; set; }
    }
}
