//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.CONTRASENAS = new HashSet<CONTRASENAS>();
        }
    
        public int ID_USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public string LOGIN { get; set; }
        public string CONTRASEÑA { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
        public Nullable<System.DateTime> FECHA_CADUCIDAD { get; set; }
        public int ID_PERFIL { get; set; }
        public string ESTADO { get; set; }
    
        public virtual PERFILES PERFILES { get; set; }
        public virtual ICollection<CONTRASENAS> CONTRASENAS { get; set; }
    }
}
