//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Website.HistoricosService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Paginacion", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class Paginacion : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long _dcField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string callbackField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string dirField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int limitField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int pageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string sortField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long _dc {
            get {
                return this._dcField;
            }
            set {
                if ((this._dcField.Equals(value) != true)) {
                    this._dcField = value;
                    this.RaisePropertyChanged("_dc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string callback {
            get {
                return this.callbackField;
            }
            set {
                if ((object.ReferenceEquals(this.callbackField, value) != true)) {
                    this.callbackField = value;
                    this.RaisePropertyChanged("callback");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string dir {
            get {
                return this.dirField;
            }
            set {
                if ((object.ReferenceEquals(this.dirField, value) != true)) {
                    this.dirField = value;
                    this.RaisePropertyChanged("dir");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int limit {
            get {
                return this.limitField;
            }
            set {
                if ((this.limitField.Equals(value) != true)) {
                    this.limitField = value;
                    this.RaisePropertyChanged("limit");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int page {
            get {
                return this.pageField;
            }
            set {
                if ((this.pageField.Equals(value) != true)) {
                    this.pageField = value;
                    this.RaisePropertyChanged("page");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string sort {
            get {
                return this.sortField;
            }
            set {
                if ((object.ReferenceEquals(this.sortField, value) != true)) {
                    this.sortField = value;
                    this.RaisePropertyChanged("sort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int start {
            get {
                return this.startField;
            }
            set {
                if ((this.startField.Equals(value) != true)) {
                    this.startField = value;
                    this.RaisePropertyChanged("start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltrosModelOfKardexModelRb2EILji", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class FiltrosModelOfKardexModelRb2EILji : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ComparadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ContieneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, object> DiccionarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.HistoricosService.KardexModel EntidadField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] EstadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_FINALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHA_INICIALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperadorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PredicadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] UnidadesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comparador {
            get {
                return this.ComparadorField;
            }
            set {
                if ((object.ReferenceEquals(this.ComparadorField, value) != true)) {
                    this.ComparadorField = value;
                    this.RaisePropertyChanged("Comparador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Contiene {
            get {
                return this.ContieneField;
            }
            set {
                if ((object.ReferenceEquals(this.ContieneField, value) != true)) {
                    this.ContieneField = value;
                    this.RaisePropertyChanged("Contiene");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, object> Diccionario {
            get {
                return this.DiccionarioField;
            }
            set {
                if ((object.ReferenceEquals(this.DiccionarioField, value) != true)) {
                    this.DiccionarioField = value;
                    this.RaisePropertyChanged("Diccionario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.HistoricosService.KardexModel Entidad {
            get {
                return this.EntidadField;
            }
            set {
                if ((object.ReferenceEquals(this.EntidadField, value) != true)) {
                    this.EntidadField = value;
                    this.RaisePropertyChanged("Entidad");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Estados {
            get {
                return this.EstadosField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadosField, value) != true)) {
                    this.EstadosField = value;
                    this.RaisePropertyChanged("Estados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_FINAL {
            get {
                return this.FECHA_FINALField;
            }
            set {
                if ((this.FECHA_FINALField.Equals(value) != true)) {
                    this.FECHA_FINALField = value;
                    this.RaisePropertyChanged("FECHA_FINAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA_INICIAL {
            get {
                return this.FECHA_INICIALField;
            }
            set {
                if ((this.FECHA_INICIALField.Equals(value) != true)) {
                    this.FECHA_INICIALField = value;
                    this.RaisePropertyChanged("FECHA_INICIAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Operador {
            get {
                return this.OperadorField;
            }
            set {
                if ((object.ReferenceEquals(this.OperadorField, value) != true)) {
                    this.OperadorField = value;
                    this.RaisePropertyChanged("Operador");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Predicado {
            get {
                return this.PredicadoField;
            }
            set {
                if ((object.ReferenceEquals(this.PredicadoField, value) != true)) {
                    this.PredicadoField = value;
                    this.RaisePropertyChanged("Predicado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Unidades {
            get {
                return this.UnidadesField;
            }
            set {
                if ((object.ReferenceEquals(this.UnidadesField, value) != true)) {
                    this.UnidadesField = value;
                    this.RaisePropertyChanged("Unidades");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KardexModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class KardexModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_ITEMField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_ITEM_NO_OPERABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_ITEM_OPERABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MAT_BELICOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_MUNICION_UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_ITEM {
            get {
                return this.ID_ITEMField;
            }
            set {
                if ((this.ID_ITEMField.Equals(value) != true)) {
                    this.ID_ITEMField = value;
                    this.RaisePropertyChanged("ID_ITEM");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_ITEM_NO_OPERABLE {
            get {
                return this.ID_ITEM_NO_OPERABLEField;
            }
            set {
                if ((this.ID_ITEM_NO_OPERABLEField.Equals(value) != true)) {
                    this.ID_ITEM_NO_OPERABLEField = value;
                    this.RaisePropertyChanged("ID_ITEM_NO_OPERABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_ITEM_OPERABLE {
            get {
                return this.ID_ITEM_OPERABLEField;
            }
            set {
                if ((this.ID_ITEM_OPERABLEField.Equals(value) != true)) {
                    this.ID_ITEM_OPERABLEField = value;
                    this.RaisePropertyChanged("ID_ITEM_OPERABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MAT_BELICO {
            get {
                return this.ID_MAT_BELICOField;
            }
            set {
                if ((this.ID_MAT_BELICOField.Equals(value) != true)) {
                    this.ID_MAT_BELICOField = value;
                    this.RaisePropertyChanged("ID_MAT_BELICO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_MUNICION_UNIDAD {
            get {
                return this.ID_MUNICION_UNIDADField;
            }
            set {
                if ((this.ID_MUNICION_UNIDADField.Equals(value) != true)) {
                    this.ID_MUNICION_UNIDADField = value;
                    this.RaisePropertyChanged("ID_MUNICION_UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="HistoricoVerificacionModelResp", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Servicio.Models")]
    [System.SerializableAttribute()]
    public partial class HistoricoVerificacionModelResp : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AERONAVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FABRICANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GRUPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HORA_ACTUALField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HORA_ANTERIORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_SERIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RESPONSABLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_COMPONENTEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AERONAVE {
            get {
                return this.AERONAVEField;
            }
            set {
                if ((object.ReferenceEquals(this.AERONAVEField, value) != true)) {
                    this.AERONAVEField = value;
                    this.RaisePropertyChanged("AERONAVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FABRICANTE {
            get {
                return this.FABRICANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.FABRICANTEField, value) != true)) {
                    this.FABRICANTEField = value;
                    this.RaisePropertyChanged("FABRICANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GRUPO {
            get {
                return this.GRUPOField;
            }
            set {
                if ((object.ReferenceEquals(this.GRUPOField, value) != true)) {
                    this.GRUPOField = value;
                    this.RaisePropertyChanged("GRUPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HORA_ACTUAL {
            get {
                return this.HORA_ACTUALField;
            }
            set {
                if ((object.ReferenceEquals(this.HORA_ACTUALField, value) != true)) {
                    this.HORA_ACTUALField = value;
                    this.RaisePropertyChanged("HORA_ACTUAL");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HORA_ANTERIOR {
            get {
                return this.HORA_ANTERIORField;
            }
            set {
                if ((object.ReferenceEquals(this.HORA_ANTERIORField, value) != true)) {
                    this.HORA_ANTERIORField = value;
                    this.RaisePropertyChanged("HORA_ANTERIOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_SERIE {
            get {
                return this.NRO_SERIEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_SERIEField, value) != true)) {
                    this.NRO_SERIEField = value;
                    this.RaisePropertyChanged("NRO_SERIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACION {
            get {
                return this.OBSERVACIONField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONField, value) != true)) {
                    this.OBSERVACIONField = value;
                    this.RaisePropertyChanged("OBSERVACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RESPONSABLE {
            get {
                return this.RESPONSABLEField;
            }
            set {
                if ((object.ReferenceEquals(this.RESPONSABLEField, value) != true)) {
                    this.RESPONSABLEField = value;
                    this.RaisePropertyChanged("RESPONSABLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_COMPONENTE {
            get {
                return this.TIPO_COMPONENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_COMPONENTEField, value) != true)) {
                    this.TIPO_COMPONENTEField = value;
                    this.RaisePropertyChanged("TIPO_COMPONENTE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private EMI.Website.HistoricosService.HistoricoVerificacionModelResp[] datosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool successField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int totalField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public EMI.Website.HistoricosService.HistoricoVerificacionModelResp[] datos {
            get {
                return this.datosField;
            }
            set {
                if ((object.ReferenceEquals(this.datosField, value) != true)) {
                    this.datosField = value;
                    this.RaisePropertyChanged("datos");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string msg {
            get {
                return this.msgField;
            }
            set {
                if ((object.ReferenceEquals(this.msgField, value) != true)) {
                    this.msgField = value;
                    this.RaisePropertyChanged("msg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success {
            get {
                return this.successField;
            }
            set {
                if ((this.successField.Equals(value) != true)) {
                    this.successField = value;
                    this.RaisePropertyChanged("success");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int total {
            get {
                return this.totalField;
            }
            set {
                if ((this.totalField.Equals(value) != true)) {
                    this.totalField = value;
                    this.RaisePropertyChanged("total");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="HistoricosService.IHistoricos")]
    public interface IHistoricos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricos/ObtenerHistoricoVerificacionMatLogisticoPaginados", ReplyAction="http://tempuri.org/IHistoricos/ObtenerHistoricoVerificacionMatLogisticoPaginadosR" +
            "esponse")]
        EMI.Website.HistoricosService.ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn ObtenerHistoricoVerificacionMatLogisticoPaginados(EMI.Website.HistoricosService.Paginacion paginacion, EMI.Website.HistoricosService.FiltrosModelOfKardexModelRb2EILji filtros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IHistoricos/ObtenerHistoricoVerificacionMatLogisticoPaginados", ReplyAction="http://tempuri.org/IHistoricos/ObtenerHistoricoVerificacionMatLogisticoPaginadosR" +
            "esponse")]
        System.Threading.Tasks.Task<EMI.Website.HistoricosService.ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn> ObtenerHistoricoVerificacionMatLogisticoPaginadosAsync(EMI.Website.HistoricosService.Paginacion paginacion, EMI.Website.HistoricosService.FiltrosModelOfKardexModelRb2EILji filtros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IHistoricosChannel : EMI.Website.HistoricosService.IHistoricos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HistoricosClient : System.ServiceModel.ClientBase<EMI.Website.HistoricosService.IHistoricos>, EMI.Website.HistoricosService.IHistoricos {
        
        public HistoricosClient() {
        }
        
        public HistoricosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HistoricosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HistoricosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public EMI.Website.HistoricosService.ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn ObtenerHistoricoVerificacionMatLogisticoPaginados(EMI.Website.HistoricosService.Paginacion paginacion, EMI.Website.HistoricosService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerHistoricoVerificacionMatLogisticoPaginados(paginacion, filtros);
        }
        
        public System.Threading.Tasks.Task<EMI.Website.HistoricosService.ListasServicioOfHistoricoVerificacionModelRespLLZUzu_Sn> ObtenerHistoricoVerificacionMatLogisticoPaginadosAsync(EMI.Website.HistoricosService.Paginacion paginacion, EMI.Website.HistoricosService.FiltrosModelOfKardexModelRb2EILji filtros) {
            return base.Channel.ObtenerHistoricoVerificacionMatLogisticoPaginadosAsync(paginacion, filtros);
        }
    }
}
