Ext.define('App.Model.Erp.Clientes', {
    extend: 'Ext.data.Model',
    fields: [
        { name: 'IDCLIENTE', type: 'int' },
        { name: 'RAZON_SOCIAL' },
        //{ name: 'FECHA_ALTA', type: 'date' },
        { name: 'ESPERSONA' },
        { name: 'APELLIDOS' },
        { name: 'NOMBRES' },
        { name: 'NOMBRE_COMPLETO' },
        //{ name: 'FECHA_NACIM', type: 'date' },
        { name: 'IDTIPODOC' },
        { name: 'NRODOCUMENTO' },
        { name: 'SEXO' },
        { name: 'ESTADO_CIVIL' },
        { name: 'IDTRAMITE' },
        { name: 'RAM_ORIG' },
        { name: 'IDTIPO_TRAM' },
        { name: 'IDSUMINISTRO' },
        { name: 'IDZONA' },
        { name: 'IDSTATUS' },
        { name: 'NROTRAMITE' },
        { name: 'FINALIZADO' },
        { name: 'IDCBTE' },
        { name: 'IDCALLE' },
        { name: 'CALLE'},
        { name: 'NROPUERTA'},
        { name: 'ENTRE_CALLES' },
        { name: 'IDGRUPO'},
        { name: 'IDRUTA'},
        { name: 'IDCATEGORIA' },
        { name: 'TELEFONOS' }
    ]
});