//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BITACORAS
    {
        public int ID_HIST { get; set; }
        public string TABLA { get; set; }
        public int ID_TABLA { get; set; }
        public string COLUMNA { get; set; }
        public string VALOR { get; set; }
        public string LOGIN { get; set; }
        public System.DateTime FECHA { get; set; }
        public string ACCION { get; set; }
    }
}
