//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONTRASENAS
    {
        public int ID_CONTRASENA { get; set; }
        public int ID_USUARIO { get; set; }
        public string CONTRASENA { get; set; }
        public System.DateTime FECHA_ALTA { get; set; }
        public System.DateTime FECHA_EXPIRACION { get; set; }
        public string ESTADO { get; set; }
        public int NRO_FALLIDO { get; set; }
        public Nullable<System.DateTime> FECHA_BLOQUEO { get; set; }
    
        public virtual USUARIOS USUARIOS { get; set; }
    }
}
