//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DESPACHOS
    {
        public int ID_DESPACHO { get; set; }
        public int ID_DETALLE { get; set; }
        public int CANTIDAD_ENTREGADA { get; set; }
        public int SALDO { get; set; }
        public string LOGIN { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime FECHA_REG { get; set; }
        public Nullable<int> ID_ITEM_ARMAMENTO { get; set; }
        public Nullable<int> ID_ITEM_LOGISTICO { get; set; }
        public string ESTADO { get; set; }
        public string LOGIN_RECEP { get; set; }
    
        public virtual DETALLES_PEDIDOS DETALLES_PEDIDOS { get; set; }
        public virtual ITEMS_ARMAMENTO ITEMS_ARMAMENTO { get; set; }
        public virtual ITEMS_MAT_LOGISTICOS ITEMS_MAT_LOGISTICOS { get; set; }
    }
}
