//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HISTORICO_CMP
    {
        public int ID_HIST { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_ITEM_OPERABLE { get; set; }
        public string CMP_OPERABLE { get; set; }
        public int ID_ITEM_NO_OPERABLE { get; set; }
        public string CMP_NO_OPERABLE { get; set; }
        public string OBSERVACION { get; set; }
        public string LOGIN { get; set; }
    
        public virtual ITEMS_ARMAMENTO ITEMS_ARMAMENTO { get; set; }
        public virtual ITEMS_ARMAMENTO ITEMS_ARMAMENTO1 { get; set; }
    }
}
