//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_ARMAMENTO
    {
        public ITEMS_ARMAMENTO()
        {
            this.COMPONENTES_ITEMS = new HashSet<COMPONENTES_ITEMS>();
            this.HISTORICO_CMP = new HashSet<HISTORICO_CMP>();
            this.HISTORICO_CMP1 = new HashSet<HISTORICO_CMP>();
            this.DESPACHOS = new HashSet<DESPACHOS>();
        }
    
        public int ID_ITEM { get; set; }
        public Nullable<int> ID_MAT_BELICO { get; set; }
        public string NRO_FUSIL { get; set; }
        public Nullable<System.DateTime> FECHA_BAJA { get; set; }
        public string OBSERVACION_BAJA { get; set; }
        public Nullable<System.DateTime> FECHA_REG { get; set; }
        public Nullable<int> ID_UNIDAD { get; set; }
        public string LOGIN { get; set; }
        public string ESTADO { get; set; }
        public string LOGIN_BAJA { get; set; }
    
        public virtual ICollection<COMPONENTES_ITEMS> COMPONENTES_ITEMS { get; set; }
        public virtual ICollection<HISTORICO_CMP> HISTORICO_CMP { get; set; }
        public virtual ICollection<HISTORICO_CMP> HISTORICO_CMP1 { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
        public virtual MAT_BELICOS MAT_BELICOS { get; set; }
        public virtual ICollection<DESPACHOS> DESPACHOS { get; set; }
    }
}
