//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEMS_VERIFICACIONES
    {
        public int ID_VERIFICACION { get; set; }
        public int ID_ITEM { get; set; }
        public string VALOR_NUEVO { get; set; }
        public string VALOR_ANTERIOR { get; set; }
        public string LOGIN { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public System.DateTime FECHA_REG { get; set; }
        public string OBSERVACION { get; set; }
    
        public virtual ITEMS_MAT_LOGISTICOS ITEMS_MAT_LOGISTICOS { get; set; }
    }
}
