//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTAS1
    {
        public LISTAS1()
        {
            this.LISTAS_ITEMS = new HashSet<LISTAS_ITEMS>();
        }
    
        public int ID_LISTA { get; set; }
        public string LISTA { get; set; }
        public string DESCRIPCION { get; set; }
        public int TAM_LIMITE { get; set; }
        public string TIPO_VALOR { get; set; }
        public string MAYUS_MINUS { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<LISTAS_ITEMS> LISTAS_ITEMS { get; set; }
    }
}
