//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class LISTAS_ITEMS
    {
        public LISTAS_ITEMS()
        {
            this.LISTAS_ITEMS1 = new HashSet<LISTAS_ITEMS>();
        }
    
        public int ID_TABLA { get; set; }
        public Nullable<int> ID_PADRE { get; set; }
        public int ID_LISTA { get; set; }
        public string CODIGO { get; set; }
        public string VALOR { get; set; }
        public string ESTADO { get; set; }
    
        public virtual LISTAS1 LISTAS1 { get; set; }
        public virtual ICollection<LISTAS_ITEMS> LISTAS_ITEMS1 { get; set; }
        public virtual LISTAS_ITEMS LISTAS_ITEMS2 { get; set; }
    }
}
