//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAT_BELICOS
    {
        public MAT_BELICOS()
        {
            this.DETALLES_PEDIDOS = new HashSet<DETALLES_PEDIDOS>();
            this.ITEMS_ARMAMENTO = new HashSet<ITEMS_ARMAMENTO>();
            this.MOV_MAT_BELICOS = new HashSet<MOV_MAT_BELICOS>();
            this.MUNICIONES_UNIDADES = new HashSet<MUNICIONES_UNIDADES>();
            this.PARTES_MAT_BELICOS = new HashSet<PARTES_MAT_BELICOS>();
        }
    
        public int ID_MAT_BELICO { get; set; }
        public string CODIGO { get; set; }
        public string FABRICACION { get; set; }
        public string CALIBRE { get; set; }
        public string CATEGORIA { get; set; }
        public string NOMBRE { get; set; }
        public Nullable<int> CANTIDAD_DISPONIBLE { get; set; }
        public System.DateTime FECHA_DOTACION { get; set; }
        public string OBSERVACION { get; set; }
        public System.DateTime FECHA_REG { get; set; }
        public string LOGIN { get; set; }
        public string TIPO { get; set; }
    
        public virtual ICollection<DETALLES_PEDIDOS> DETALLES_PEDIDOS { get; set; }
        public virtual ICollection<ITEMS_ARMAMENTO> ITEMS_ARMAMENTO { get; set; }
        public virtual ICollection<MOV_MAT_BELICOS> MOV_MAT_BELICOS { get; set; }
        public virtual ICollection<MUNICIONES_UNIDADES> MUNICIONES_UNIDADES { get; set; }
        public virtual ICollection<PARTES_MAT_BELICOS> PARTES_MAT_BELICOS { get; set; }
    }
}
