//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATERIALES_BELICOS
    {
        public int ID_MATERIAL { get; set; }
        public string CODIGO_MATERIAL { get; set; }
        public string ARMAMENTO { get; set; }
        public string CALIBRE { get; set; }
        public string ESTADO { get; set; }
        public string FABRICACION { get; set; }
        public System.DateTime FECHA_DOTACION { get; set; }
        public Nullable<System.DateTime> FECHA_MODIFICACION { get; set; }
        public string UNIDAD { get; set; }
    }
}
