//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU_OPCIONES
    {
        public MENU_OPCIONES()
        {
            this.PERFILES_OPCIONES = new HashSet<PERFILES_OPCIONES>();
        }
    
        public int ID_MENU { get; set; }
        public string MENU { get; set; }
        public string CLASE { get; set; }
        public string TOOLTIP { get; set; }
        public string ICONCCS { get; set; }
        public Nullable<int> ID_PADRE { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<PERFILES_OPCIONES> PERFILES_OPCIONES { get; set; }
    }
}
