//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmiEntities : DbContext
    {
        public EmiEntities()
            : base("name=EmiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<PERFILES> PERFILES { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<MENU_OPCIONES> MENU_OPCIONES { get; set; }
        public DbSet<PERFILES_OPCIONES> PERFILES_OPCIONES { get; set; }
        public DbSet<MATERIALES_BELICOS> MATERIALES_BELICOS { get; set; }
        public DbSet<COMPONENTES_ITEMS> COMPONENTES_ITEMS { get; set; }
        public DbSet<DETALLES_PEDIDOS> DETALLES_PEDIDOS { get; set; }
        public DbSet<HISTORICO_CMP> HISTORICO_CMP { get; set; }
        public DbSet<HISTORICOS_PEDIDOS> HISTORICOS_PEDIDOS { get; set; }
        public DbSet<ITEMS_VERIFICACIONES> ITEMS_VERIFICACIONES { get; set; }
        public DbSet<MAT_LOGISTICOS> MAT_LOGISTICOS { get; set; }
        public DbSet<MOV_MAT_BELICOS> MOV_MAT_BELICOS { get; set; }
        public DbSet<MOV_MUNICIONES_UNIDADES> MOV_MUNICIONES_UNIDADES { get; set; }
        public DbSet<MUNICIONES_UNIDADES> MUNICIONES_UNIDADES { get; set; }
        public DbSet<PARTES_MAT_BELICOS> PARTES_MAT_BELICOS { get; set; }
        public DbSet<PEDIDOS> PEDIDOS { get; set; }
        public DbSet<SALIDADES_MUNICIONES> SALIDADES_MUNICIONES { get; set; }
        public DbSet<UNIDADES> UNIDADES { get; set; }
        public DbSet<LISTAS1> LISTAS1 { get; set; }
        public DbSet<ITEMS_ARMAMENTO> ITEMS_ARMAMENTO { get; set; }
        public DbSet<LISTAS_ITEMS> LISTAS_ITEMS { get; set; }
        public DbSet<MAT_BELICOS> MAT_BELICOS { get; set; }
        public DbSet<ITEMS_MAT_LOGISTICOS> ITEMS_MAT_LOGISTICOS { get; set; }
        public DbSet<DESPACHOS> DESPACHOS { get; set; }
        public DbSet<CONTRASENAS> CONTRASENAS { get; set; }
        public DbSet<BITACORAS> BITACORAS { get; set; }
    }
}
