//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MOV_MAT_BELICOS
    {
        public int ID_MOV { get; set; }
        public System.DateTime FECHA { get; set; }
        public int ID_MAT_BELICO { get; set; }
        public int ENTRADA { get; set; }
        public int SALIDA { get; set; }
        public int SALDO { get; set; }
        public string OPERACION { get; set; }
        public int ID_OPERACION { get; set; }
        public string LOGIN { get; set; }
    
        public virtual MAT_BELICOS MAT_BELICOS { get; set; }
    }
}
