//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDOS
    {
        public PEDIDOS()
        {
            this.DETALLES_PEDIDOS = new HashSet<DETALLES_PEDIDOS>();
            this.HISTORICOS_PEDIDOS = new HashSet<HISTORICOS_PEDIDOS>();
        }
    
        public int ID_PEDIDO { get; set; }
        public int NRO_PEDIDO { get; set; }
        public string TIPO { get; set; }
        public int ID_UNIDAD { get; set; }
        public System.DateTime FECHA_PEDIDO { get; set; }
        public string OBSERVACIONES { get; set; }
        public string LOGIN { get; set; }
        public System.DateTime FECHA_REG { get; set; }
        public Nullable<System.DateTime> FECHA_MODIF { get; set; }
        public string ESTADO { get; set; }
    
        public virtual ICollection<DETALLES_PEDIDOS> DETALLES_PEDIDOS { get; set; }
        public virtual ICollection<HISTORICOS_PEDIDOS> HISTORICOS_PEDIDOS { get; set; }
        public virtual UNIDADES UNIDADES { get; set; }
    }
}
