//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILES_OPCIONES
    {
        public int ID_OPC_MEN { get; set; }
        public int ID_MENU { get; set; }
        public int ID_PERFIL { get; set; }
    
        public virtual MENU_OPCIONES MENU_OPCIONES { get; set; }
        public virtual PERFILES PERFILES { get; set; }
    }
}
