//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMI.Wcf.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UNIDADES
    {
        public UNIDADES()
        {
            this.MUNICIONES_UNIDADES = new HashSet<MUNICIONES_UNIDADES>();
            this.PEDIDOS = new HashSet<PEDIDOS>();
            this.PERFILES = new HashSet<PERFILES>();
            this.ITEMS_ARMAMENTO = new HashSet<ITEMS_ARMAMENTO>();
            this.ITEMS_MAT_LOGISTICOS = new HashSet<ITEMS_MAT_LOGISTICOS>();
        }
    
        public int ID_UNIDAD { get; set; }
        public string UNIDAD { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<MUNICIONES_UNIDADES> MUNICIONES_UNIDADES { get; set; }
        public virtual ICollection<PEDIDOS> PEDIDOS { get; set; }
        public virtual ICollection<PERFILES> PERFILES { get; set; }
        public virtual ICollection<ITEMS_ARMAMENTO> ITEMS_ARMAMENTO { get; set; }
        public virtual ICollection<ITEMS_MAT_LOGISTICOS> ITEMS_MAT_LOGISTICOS { get; set; }
    }
}
