//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18408
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Emi.Wcf.Servicio.Test.ReportesService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ExistenciasModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class ExistenciasModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ALTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int BAJASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int EXISTENCIA_ANTERIORField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GRUPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_UNIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOTAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PERDIDASField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ALTA {
            get {
                return this.ALTAField;
            }
            set {
                if ((this.ALTAField.Equals(value) != true)) {
                    this.ALTAField = value;
                    this.RaisePropertyChanged("ALTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BAJAS {
            get {
                return this.BAJASField;
            }
            set {
                if ((this.BAJASField.Equals(value) != true)) {
                    this.BAJASField = value;
                    this.RaisePropertyChanged("BAJAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DETALLE {
            get {
                return this.DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLEField, value) != true)) {
                    this.DETALLEField = value;
                    this.RaisePropertyChanged("DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int EXISTENCIA_ANTERIOR {
            get {
                return this.EXISTENCIA_ANTERIORField;
            }
            set {
                if ((this.EXISTENCIA_ANTERIORField.Equals(value) != true)) {
                    this.EXISTENCIA_ANTERIORField = value;
                    this.RaisePropertyChanged("EXISTENCIA_ANTERIOR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GRUPO {
            get {
                return this.GRUPOField;
            }
            set {
                if ((object.ReferenceEquals(this.GRUPOField, value) != true)) {
                    this.GRUPOField = value;
                    this.RaisePropertyChanged("GRUPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DETALLE {
            get {
                return this.ID_DETALLEField;
            }
            set {
                if ((this.ID_DETALLEField.Equals(value) != true)) {
                    this.ID_DETALLEField = value;
                    this.RaisePropertyChanged("ID_DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_UNIDAD {
            get {
                return this.ID_UNIDADField;
            }
            set {
                if ((this.ID_UNIDADField.Equals(value) != true)) {
                    this.ID_UNIDADField = value;
                    this.RaisePropertyChanged("ID_UNIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOTA {
            get {
                return this.NOTAField;
            }
            set {
                if ((object.ReferenceEquals(this.NOTAField, value) != true)) {
                    this.NOTAField = value;
                    this.RaisePropertyChanged("NOTA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PERDIDAS {
            get {
                return this.PERDIDASField;
            }
            set {
                if ((this.PERDIDASField.Equals(value) != true)) {
                    this.PERDIDASField = value;
                    this.RaisePropertyChanged("PERDIDAS");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDAD {
            get {
                return this.UNIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADField, value) != true)) {
                    this.UNIDADField = value;
                    this.RaisePropertyChanged("UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetallePedidoModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class DetallePedidoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANTIDAD_ENTREGADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CANTIDAD_SOLICITADAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CATEGORIAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_DETALLEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADO_RECEPCIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_FINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_INIField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_PEDIDOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANTIDAD_ENTREGADA {
            get {
                return this.CANTIDAD_ENTREGADAField;
            }
            set {
                if ((this.CANTIDAD_ENTREGADAField.Equals(value) != true)) {
                    this.CANTIDAD_ENTREGADAField = value;
                    this.RaisePropertyChanged("CANTIDAD_ENTREGADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CANTIDAD_SOLICITADA {
            get {
                return this.CANTIDAD_SOLICITADAField;
            }
            set {
                if ((this.CANTIDAD_SOLICITADAField.Equals(value) != true)) {
                    this.CANTIDAD_SOLICITADAField = value;
                    this.RaisePropertyChanged("CANTIDAD_SOLICITADA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CATEGORIA {
            get {
                return this.CATEGORIAField;
            }
            set {
                if ((object.ReferenceEquals(this.CATEGORIAField, value) != true)) {
                    this.CATEGORIAField = value;
                    this.RaisePropertyChanged("CATEGORIA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DETALLE {
            get {
                return this.DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.DETALLEField, value) != true)) {
                    this.DETALLEField = value;
                    this.RaisePropertyChanged("DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_DETALLE {
            get {
                return this.ESTADO_DETALLEField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_DETALLEField, value) != true)) {
                    this.ESTADO_DETALLEField = value;
                    this.RaisePropertyChanged("ESTADO_DETALLE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO_RECEPCION {
            get {
                return this.ESTADO_RECEPCIONField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADO_RECEPCIONField, value) != true)) {
                    this.ESTADO_RECEPCIONField = value;
                    this.RaisePropertyChanged("ESTADO_RECEPCION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA {
            get {
                return this.FECHAField;
            }
            set {
                if ((this.FECHAField.Equals(value) != true)) {
                    this.FECHAField = value;
                    this.RaisePropertyChanged("FECHA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_FIN {
            get {
                return this.FECHA_FINField;
            }
            set {
                if ((this.FECHA_FINField.Equals(value) != true)) {
                    this.FECHA_FINField = value;
                    this.RaisePropertyChanged("FECHA_FIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_INI {
            get {
                return this.FECHA_INIField;
            }
            set {
                if ((this.FECHA_INIField.Equals(value) != true)) {
                    this.FECHA_INIField = value;
                    this.RaisePropertyChanged("FECHA_INI");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_PEDIDO {
            get {
                return this.ID_PEDIDOField;
            }
            set {
                if ((this.ID_PEDIDOField.Equals(value) != true)) {
                    this.ID_PEDIDOField = value;
                    this.RaisePropertyChanged("ID_PEDIDO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDAD {
            get {
                return this.UNIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADField, value) != true)) {
                    this.UNIDADField = value;
                    this.RaisePropertyChanged("UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatLogisticoModel", Namespace="http://schemas.datacontract.org/2004/07/EMI.Wcf.Aplicacion.Modelo")]
    [System.SerializableAttribute()]
    public partial class MatLogisticoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AERONAVEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> CICLO_VIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CODIGOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ESTADOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FABRICANTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FECHA_DOTACIONField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GRUPOField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> HORA_VIDAField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ID_ITEM_Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> ID_UNIDADField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_PARTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NRO_SERIEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OBSERVACIONESField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TIPO_COMPONENTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UNIDADField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AERONAVE {
            get {
                return this.AERONAVEField;
            }
            set {
                if ((object.ReferenceEquals(this.AERONAVEField, value) != true)) {
                    this.AERONAVEField = value;
                    this.RaisePropertyChanged("AERONAVE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CICLO_VIDA {
            get {
                return this.CICLO_VIDAField;
            }
            set {
                if ((this.CICLO_VIDAField.Equals(value) != true)) {
                    this.CICLO_VIDAField = value;
                    this.RaisePropertyChanged("CICLO_VIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CODIGO {
            get {
                return this.CODIGOField;
            }
            set {
                if ((object.ReferenceEquals(this.CODIGOField, value) != true)) {
                    this.CODIGOField = value;
                    this.RaisePropertyChanged("CODIGO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ESTADO {
            get {
                return this.ESTADOField;
            }
            set {
                if ((object.ReferenceEquals(this.ESTADOField, value) != true)) {
                    this.ESTADOField = value;
                    this.RaisePropertyChanged("ESTADO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FABRICANTE {
            get {
                return this.FABRICANTEField;
            }
            set {
                if ((object.ReferenceEquals(this.FABRICANTEField, value) != true)) {
                    this.FABRICANTEField = value;
                    this.RaisePropertyChanged("FABRICANTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FECHA_DOTACION {
            get {
                return this.FECHA_DOTACIONField;
            }
            set {
                if ((this.FECHA_DOTACIONField.Equals(value) != true)) {
                    this.FECHA_DOTACIONField = value;
                    this.RaisePropertyChanged("FECHA_DOTACION");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GRUPO {
            get {
                return this.GRUPOField;
            }
            set {
                if ((object.ReferenceEquals(this.GRUPOField, value) != true)) {
                    this.GRUPOField = value;
                    this.RaisePropertyChanged("GRUPO");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> HORA_VIDA {
            get {
                return this.HORA_VIDAField;
            }
            set {
                if ((this.HORA_VIDAField.Equals(value) != true)) {
                    this.HORA_VIDAField = value;
                    this.RaisePropertyChanged("HORA_VIDA");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_ITEM_ {
            get {
                return this.ID_ITEM_Field;
            }
            set {
                if ((this.ID_ITEM_Field.Equals(value) != true)) {
                    this.ID_ITEM_Field = value;
                    this.RaisePropertyChanged("ID_ITEM_");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> ID_UNIDAD {
            get {
                return this.ID_UNIDADField;
            }
            set {
                if ((this.ID_UNIDADField.Equals(value) != true)) {
                    this.ID_UNIDADField = value;
                    this.RaisePropertyChanged("ID_UNIDAD");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_PARTE {
            get {
                return this.NRO_PARTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_PARTEField, value) != true)) {
                    this.NRO_PARTEField = value;
                    this.RaisePropertyChanged("NRO_PARTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NRO_SERIE {
            get {
                return this.NRO_SERIEField;
            }
            set {
                if ((object.ReferenceEquals(this.NRO_SERIEField, value) != true)) {
                    this.NRO_SERIEField = value;
                    this.RaisePropertyChanged("NRO_SERIE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OBSERVACIONES {
            get {
                return this.OBSERVACIONESField;
            }
            set {
                if ((object.ReferenceEquals(this.OBSERVACIONESField, value) != true)) {
                    this.OBSERVACIONESField = value;
                    this.RaisePropertyChanged("OBSERVACIONES");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TIPO_COMPONENTE {
            get {
                return this.TIPO_COMPONENTEField;
            }
            set {
                if ((object.ReferenceEquals(this.TIPO_COMPONENTEField, value) != true)) {
                    this.TIPO_COMPONENTEField = value;
                    this.RaisePropertyChanged("TIPO_COMPONENTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UNIDAD {
            get {
                return this.UNIDADField;
            }
            set {
                if ((object.ReferenceEquals(this.UNIDADField, value) != true)) {
                    this.UNIDADField = value;
                    this.RaisePropertyChanged("UNIDAD");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReportesService.IReportes")]
    public interface IReportes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasArmamento", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasArmamentoResponse")]
        Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasArmamento(string ANIO, string MES, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasArmamento", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasArmamentoResponse")]
        System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasArmamentoAsync(string ANIO, string MES, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasMuniciones", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasMunicionesResponse")]
        Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasMuniciones(string ANIO, string MES, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasMuniciones", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasMunicionesResponse")]
        System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasMunicionesAsync(string ANIO, string MES, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerDetallePedido", ReplyAction="http://tempuri.org/IReportes/ObtenerDetallePedidoResponse")]
        Emi.Wcf.Servicio.Test.ReportesService.DetallePedidoModel[] ObtenerDetallePedido(System.DateTime FECHA_INI, System.DateTime FECHA_FIN, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerDetallePedido", ReplyAction="http://tempuri.org/IReportes/ObtenerDetallePedidoResponse")]
        System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.DetallePedidoModel[]> ObtenerDetallePedidoAsync(System.DateTime FECHA_INI, System.DateTime FECHA_FIN, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerMaterialesLogisticos", ReplyAction="http://tempuri.org/IReportes/ObtenerMaterialesLogisticosResponse")]
        Emi.Wcf.Servicio.Test.ReportesService.MatLogisticoModel[] ObtenerMaterialesLogisticos(int ID_MAT_LOGISTICO, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerMaterialesLogisticos", ReplyAction="http://tempuri.org/IReportes/ObtenerMaterialesLogisticosResponse")]
        System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.MatLogisticoModel[]> ObtenerMaterialesLogisticosAsync(int ID_MAT_LOGISTICO, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasMatLogisticos", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasMatLogisticosResponse")]
        Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasMatLogisticos(string ANIO, string MES, int ID_UNIDAD);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReportes/ObtenerExistenciasMatLogisticos", ReplyAction="http://tempuri.org/IReportes/ObtenerExistenciasMatLogisticosResponse")]
        System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasMatLogisticosAsync(string ANIO, string MES, int ID_UNIDAD);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReportesChannel : Emi.Wcf.Servicio.Test.ReportesService.IReportes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReportesClient : System.ServiceModel.ClientBase<Emi.Wcf.Servicio.Test.ReportesService.IReportes>, Emi.Wcf.Servicio.Test.ReportesService.IReportes {
        
        public ReportesClient() {
        }
        
        public ReportesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReportesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReportesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasArmamento(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasArmamento(ANIO, MES, ID_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasArmamentoAsync(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasArmamentoAsync(ANIO, MES, ID_UNIDAD);
        }
        
        public Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasMuniciones(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasMuniciones(ANIO, MES, ID_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasMunicionesAsync(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasMunicionesAsync(ANIO, MES, ID_UNIDAD);
        }
        
        public Emi.Wcf.Servicio.Test.ReportesService.DetallePedidoModel[] ObtenerDetallePedido(System.DateTime FECHA_INI, System.DateTime FECHA_FIN, int ID_UNIDAD) {
            return base.Channel.ObtenerDetallePedido(FECHA_INI, FECHA_FIN, ID_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.DetallePedidoModel[]> ObtenerDetallePedidoAsync(System.DateTime FECHA_INI, System.DateTime FECHA_FIN, int ID_UNIDAD) {
            return base.Channel.ObtenerDetallePedidoAsync(FECHA_INI, FECHA_FIN, ID_UNIDAD);
        }
        
        public Emi.Wcf.Servicio.Test.ReportesService.MatLogisticoModel[] ObtenerMaterialesLogisticos(int ID_MAT_LOGISTICO, int ID_UNIDAD) {
            return base.Channel.ObtenerMaterialesLogisticos(ID_MAT_LOGISTICO, ID_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.MatLogisticoModel[]> ObtenerMaterialesLogisticosAsync(int ID_MAT_LOGISTICO, int ID_UNIDAD) {
            return base.Channel.ObtenerMaterialesLogisticosAsync(ID_MAT_LOGISTICO, ID_UNIDAD);
        }
        
        public Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[] ObtenerExistenciasMatLogisticos(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasMatLogisticos(ANIO, MES, ID_UNIDAD);
        }
        
        public System.Threading.Tasks.Task<Emi.Wcf.Servicio.Test.ReportesService.ExistenciasModel[]> ObtenerExistenciasMatLogisticosAsync(string ANIO, string MES, int ID_UNIDAD) {
            return base.Channel.ObtenerExistenciasMatLogisticosAsync(ANIO, MES, ID_UNIDAD);
        }
    }
}
